In [736]:
import numpy as np
import random
import math


class Binary_classificatoin:
    def __init__(self, layers):
        self.layers = layers
        self.weights =[]
        self.bias = []
        self.h=[]
        self.a=[]
        self.res = []
        self.loss = []

        for i in range(len(self.layers)-1):
            weights_ = np.array([[random.random()]*self.layers[i] for _ in range(self.layers[i+1])])
            bias_ = np.array([random.random() for _ in range(self.layers[i+1])])
            self.weights.append(weights_)
            self.bias.append(bias_)

    def sigmoid(self, l):
        answers = []
        for value in l:
            sig = 1 / (1 + np.exp(value))
            answers.append(sig)
        return answers

    def binary_crossentropy_loss(self, y_pred, y):
        return -(y*math.log(y_pred[0])+ (1-y)*math.log(1-y_pred[0]))

    def crosentropy_gad(self, y_pred, y):
        return (( (1-y)/(1-y_pred) )-( y/y_pred ))

    def sigmoid_grad(self, l):
        answers = []
        for value in l:
            sig_g = (1 / (1 + np.exp(value)))* (1-(1 / (1 + np.exp(value))))
            answers.append(sig_g)
        return answers
        

    def forward(self, X, y):
        h_ =[]
        
        for i in range(len(X)):
            h_ = X[i]
            a_temp = []
            h_temp = []
            for j in range(len(self.weights)):
                a_= np.dot(self.weights[j], h_)+self.bias[j]
                a_temp.append(a_)
                h_= self.sigmoid(a_)
                h_temp.append(np.array(h_))
                if(j==len(self.weights)-1):
                    self.res.append(h_)
                    self.loss.append(self.binary_crossentropy_loss(h_, y[i]))
            self.h.append(h_temp)
            self.a.append(a_temp)
            
            
    def backward(self, X, y, res, learning_rate):
        for i in range(len(y)):
            dh = []
            da = []
            dw = []
            db = []
            h_g = self.crosentropy_gad(res[i][0], y[i])
            dh.append([h_g])
            a_g = res[i][0]*(1-res[i][0])
            da.append([a_g])
            for j in range(len(self.layers)-2, 0, -1):
                h_g = np.dot(self.weights[j].T, self.a[i][j])*da[-1]
                dh.append(h_g)
                a_g = self.sigmoid_grad(h_g)
                da.append(a_g)
            da.reverse() 
            dh.reverse()
            for j in range(len(self.weights)-1,-1,-1):
                if(j==0):
                    w_g = (np.array([X[i]]*self.layers[j+1]).T *da[j]).T
                else:
                    w_g = (np.array([self.h[i][j-1]]*self.layers[j+1]).T * da[j]).T
                dw.append(w_g)
            dw.reverse()
            db = da
            for i in range(len(self.weights)):
                self.weights[i] -= learning_rate* np.array(dw[i])
                self.bias[i] -= learning_rate* np.array(db[i])


    def fit(self, X, y, learning_rate, epoch):
        for _ in range(epoch-1):
            self.forward(X, y)
            self.backward(X,y, self.res, learning_rate)

        self.forward(X,y)







                

In [737]:
n = Binary_classificatoin([2,4,4,1])

In [738]:
n.forward(np.array([[1,2],[2,3]]), [1,0])

In [739]:
da, dh, dw, db = n.backward(np.array([[1,2],[2,3]]), [1,0], n.res)


In [740]:
da

[[0.24728501003748946,
  0.24728501003748946,
  0.24728501003748946,
  0.24728501003748946],
 [0.24775184595226393,
  0.24775184595226393,
  0.24775184595226393,
  0.24775184595226393],
 [0.14726587684754022]]

In [741]:
dh

[array([0.2091817, 0.2091817, 0.2091817, 0.2091817]),
 array([0.19023041, 0.19023041, 0.19023041, 0.19023041]),
 [1.2187368967555523]]

In [743]:
dw

[array([[0.49457002, 0.74185503],
        [0.49457002, 0.74185503],
        [0.49457002, 0.74185503],
        [0.49457002, 0.74185503]]),
 array([[0.02640278, 0.00131763, 0.0021075 , 0.0194176 ],
        [0.02640278, 0.00131763, 0.0021075 , 0.0194176 ],
        [0.02640278, 0.00131763, 0.0021075 , 0.0194176 ],
        [0.02640278, 0.00131763, 0.0021075 , 0.0194176 ]]),
 array([[0.05402696, 0.06834515, 0.04049331, 0.04956386]])]

In [755]:
n.weights

[array([[0.33940437, 0.33940437],
        [0.96153286, 0.96153286],
        [0.87196426, 0.87196426],
        [0.42961636, 0.42961636]]),
 array([[0.01284093, 0.01284093, 0.01284093, 0.01284093],
        [0.05683556, 0.05683556, 0.05683556, 0.05683556],
        [0.57479666, 0.57479666, 0.57479666, 0.57479666],
        [0.40054355, 0.40054355, 0.40054355, 0.40054355]]),
 array([[0.84989817, 0.84989817, 0.84989817, 0.84989817]])]

In [756]:
db

[[0.24728501003748946,
  0.24728501003748946,
  0.24728501003748946,
  0.24728501003748946],
 [0.24775184595226393,
  0.24775184595226393,
  0.24775184595226393,
  0.24775184595226393],
 [0.14726587684754022]]

In [745]:
n.bias

[array([0.42924979, 0.42359939, 0.39855873, 0.31654906]),
 array([0.54312966, 0.13257623, 0.8553122 , 0.5990444 ]),
 array([0.29391765])]

In [746]:
n.h

[[array([0.19039233, 0.03529102, 0.04677726, 0.1672285 ]),
  array([0.36614851, 0.46068974, 0.24823572, 0.31536416]),
  array([0.18608559])],
 [array([0.10656946, 0.00531833, 0.00850651, 0.07837518]),
  array([0.36686679, 0.46409356, 0.27496737, 0.33656039]),
  array([0.17947836])]]

In [804]:
n.weights[0] = n.weights[0] - 0.01* np.array(dw[0])
n.weights[1] = n.weights[1] - 0.01 * np.array(dw[1])
n.weights[2] = n.weights[2] - np.array(dw[2])

n.bias[0] = n.bias[0] - np.array(db[0])
n.bias[1] = n.bias[1] - np.array(db[1])
n.bias[2] = n.bias[2] - np.array(db[2])

In [805]:
n.weights

[array([[-5.15032285, -7.89518646],
        [-4.52819436, -7.27305797],
        [-4.61776296, -7.36262657],
        [-5.06011086, -7.80497447]]),
 array([[-0.35838215, -0.00568488, -0.01679058, -0.26017047],
        [-0.31438751,  0.03830975,  0.02720405, -0.21617584],
        [ 0.20357358,  0.55627084,  0.54516514,  0.30178525],
        [ 0.02932047,  0.38201773,  0.37091203,  0.12753215]]),
 array([[-0.17661405, -0.4486596 ,  0.08052527, -0.09181518]])]

In [806]:
n.bias

[array([-3.03274035, -3.03839075, -3.06343141, -3.14544108]),
 array([-2.92539618, -3.33594961, -2.61321365, -2.86948144]),
 array([-1.76780463])]

In [ ]:
def fit(self, X, y, learning_rate, epoch):
    